site_name: Stakater Support
docs_dir: content
site_url: https://support.stakater.com/
repo_url: https://github.com/stakater/support-docs
edit_uri: blob/main/content/
use_directory_urls: false
theme:
  logo: assets/images/favicon.svg
  favicon: assets/images/favicon.svg
nav:
  - index.md
  - plans.md
  - srf.md
  - irm.md
  - ssr.md
  - hrs.md
  - faq.md
